### ISSUE TITLE
Close all others

### ISSUE THREAD

**Issue by marcobrunodev** [artdiniz/quit-control-atom#1]
Close all others with command+option+w

**Comment by artdiniz** [comment]
Great idea! I would love a keybinding to do that.

The only problem is that I think this functionality escapes our initial proposal of preventing unintentional workspace shutdowns. This idea is more related to tabs organization. 

Also, you can achieve that without adding any plugins. You can go to `Settings > Keybindings > your keymap file`and add the desired keybindings.

**Comment by MarcoBrunoBR** [comment]
Nice :-)

**Comment by marcobrunodev** [comment]
Nice :-)
