### ISSUE TITLE
Close all tabs to the right

### ISSUE THREAD

**Issue by marcobrunodev** [artdiniz/quit-control-atom#2]
Close all tabs to the right, but I don't know what shortcut to use.

**Comment by artdiniz** [comment]
I think this functionality escapes our initial proposal of preventing unintentional workspace shutdowns. This idea is more related to tabs organization.

You can achieve that without adding any plugins. You can go to Settings > Keybindings > your keymap file and add the desired keybinding.

**Comment by MarcoBrunoBR** [comment]
Nice :-)

**Comment by marcobrunodev** [comment]
Nice :-)
